"""Constants for the Azure OpenAI GPT conversation RS-Tuned integration."""

DOMAIN = "azure_openai_conversation_rs_tuned"
CONF_ENDPOINT = "endpoint"
CONF_DEPLOYMENT_NAME = "deployment_name"
DEFAULT_LANGUAGE = "ko"
CONVERSATION_AGENT_NAME = "GPT_RS_TUNED"
API_VERSION = "2024-08-01-preview"
FIXED_ENDPOINT = "https://remote-solution-fine-tuning.openai.azure.com/"
CACHE_ENDPOINT = "https://rs-audio-router.azurewebsites.net/api/v1/cache-routing"
REGISTER_CACHE_ENDPOINT = "https://rs-audio-router.azurewebsites.net/api/v1/cache"
PATTERN_ENDPOINT = "https://rs-command-crawler.azurewebsites.net/api/v1/user-patterns"
INIT_CONVERSATION_WORD = "대화 내역 초기화"
REGISTER_CACHE_WORD = "이전 요청 캐쉬로 등록해줘"
